// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package node

import (
	"github.com/wittwitt/go.dev/demo/wire1/pool"
	"github.com/wittwitt/go.dev/demo/wire1/redis"
)

// Injectors from wire.go:

func IniPool() (*pool.Pool, error) {
	config := NewRedisConfig()
	client, err := redis.NewClient(config)
	if err != nil {
		return nil, err
	}
	poolPool, err := pool.NewPool(client)
	if err != nil {
		return nil, err
	}
	return poolPool, nil
}
